### ISSUE TITLE
DIY User Guide

### ISSUE THREAD

**Issue by rincewind205** [vospascal/pedal-arduino#1]
Hi - amazing work vospascal. 

I had been searching for this exact calibration software for my DIY Arduino pedal box.

My pedal box setup uses modified Logitech G27 pedals into an Arduino Pro Micro .

The install process is quite straightforward and only requires that you have the Arduino IDE installed.

The README provides the text which must be added to the Arduino boards "library". 

You can find this here;
C: > Program Files > Arduino > Hardware > AVR > boards.txt  

 **Be sure to Enable all permissions for the Arduino Folder in Windows otherwise the file will not save**

This **MUST** but done in order for the GUI software to detect the Arduino Pro Micro correctly.

Next, we can open the Arduino sketch "pedaal.ino". 

When it comes time to upload - potentially changing any input pins in the sketch to match your wiring we must select the correct board in the Arduino IDE software.

In the Arduino IDE Software > Tools > Boards > Select "PedalBox"

Ensure your Arduino board is connected to the correct COM Port and then upload the sketch.

Once this is uploaded you have the option to view pedal input data via the Serial Monitor within Arduino IDE.

If all is well, we can close Arduino IDE and open the PedalFX application and calibrate our pedal range / deadzones and pedal curves.

You may have to recalibrate your pedals in your game - but the PedalFX will save the pedal profile to the Arduino for desired use

**Comment by Jorge1184** [comment]
How do you change the input pins on the sketch? I can't find the exact lines in the code
