### ISSUE TITLE
Windows Not detectin input

### ISSUE THREAD

**Issue by cartman-sp69** [vospascal/pedal-arduino#10]
Hi is this project still active? 

I quite like it however I'm unable to get Windows to detect the input of the device.

The app detects the inputs 

I'm using an Arduino Leanardo with an ADS 1115

**Comment by pascalvos** [comment]
yes its still active as in in openffboard discord people are using it :) 
also it still works fine so :) you should do the steps like renaming the device micro.name=PedalBox 
@cartman-sp69 
make sure your setting the right bits for output like 16 out might be already more then enough 
the app reads the serial line :) so its probably not correctly configured and not sending the right hid values
