### ISSUE TITLE
Remaining pins as buttons

### ISSUE THREAD

**Issue by achavevirou** [vospascal/pedal-arduino#11]
By default the Pedalbox controller does not have any active buttons. When enabling one or more buttons in Pedals.h and uploading to the board, after loading the board is no longer detected. Is there no way to use the other pins on the Arduino Pro Micro or Leonardo for buttons? Should I consider the Arduino Pedalbox exclusively for pedals?

**Comment by vospascal** [comment]
its build exclusively for pedals
