### ISSUE TITLE
having issues with assetto corsa compatitione

### ISSUE THREAD

**Issue by danny1m** [vospascal/pedal-arduino#12]
seems my pedal acts badly with assetto corsa compatitione it dosent register braking with load cell work very well in other game but appears intermittant in acc. anyone else have this issue

**Comment by vospascal** [comment]
Pedals are not game specific it just sets gamepad inputs so if it works with one game and not an other it’s the problem of that game. It the gamepad does not register properly try changing the setting till it does work.

**Comment by danny1m** [comment]
Hi is there a way to get more range on my pedal I'm using a 100kg loadcell. But finding the It maxes out too soon even when calibrated to full foot force it hits the joy output 100% too early?

**Comment by danny1m** [comment]
Pedal gui does find Arduino did the renaming in avr board.txt but still shows up as micro or Leonardo if I try with that using a pro micro board can't work out where to change it
