### ISSUE TITLE
PCB project

### ISSUE THREAD

**Issue by tomsikk** [vospascal/pedal-arduino#7]
Part, I really like this design. Is pcb design for electronics available? If so I would like to get it

**Comment by ParronS3** [comment]
mmmmm what? PCB is simply an arduino micro, and readed on other issue that arduino leonardo works aswell.... If you want a custom form factor PCB you can design it with the arduino schematics.

**Comment by tomsikk** [comment]
I will probably do that. I like to have everything securely mounted on the pcb because I have bad memories with connecting cables. If I remember, I'll share this project here when I'm done 😊

**Comment by vospascal** [comment]
there no pcb sorry just arduino
