### ISSUE TITLE
Load cell ADC issue

### ISSUE THREAD

**Issue by Duce55** [vospascal/pedal-arduino#9]
Hi,
I have issue when connecting load cell via amp made with LM324 as ins.op.amp. I changes inputs to ADC but with ADC1115 it is not working. When configured as analog input works but digital not. During calibration I notice that throttle is working and it is super sensitive and brake is showing movement but it is out of calibration range. 
I'm using beam load cell YZC-1B.
Please can you help me with this issue, I assume that I need to change something more in code but I'm not familiar with Arduino coding.
Thank you
BR

@Attached I'm sending pedals picture. Pedals are made in my garage with hand tools!!! 

![69669bd2-2c19-4732-acb8-4a96f427d532](https://github.com/vospascal/pedal-arduino/assets/56155945/206acc5e-4f06-456f-9d37-ee45bfa4918f)

![4d06c2df-bbb5-459a-a1d7-b703067fdab1](https://github.com/vospascal/pedal-arduino/assets/56155945/501d979f-b95c-4c2d-8c34-09efa55943f6)

**Comment by Duce55** [comment]
Hi,
I succeeded by method changing some things connected to ADS and pedals assignment in code. Several mistakes but at final pedals are working in 16bit resolution!

**Comment by vospascal** [comment]
good job can you share a diagram how you changed it and how it works now so people can learn from it :) @Duce55 
also your pedals looks awesome :) love the shine 👍🏻

**Comment by Duce55** [comment]
Hi Pascal,

 

I'm very glad that you contact me, but unfortunately, I don't have good news and for last couple of days I'm struggling with coding.

 

Attached I'm sending you code that I use when I wrote „good news“.  

 

What I did:

 

Pedalbox.ino file 

 

I changed ADS inputs 2 for throttle (ADS A2 pin), 1 for brake (ADS A1 pin), clutch disabled.

 



Pedal.h file



 

Pedals.h file



                                                            


And



Startup PedalFX calibrated pedals and throttle, brake pedal finally working!!! 

 

I was not happy that clutch was working as same as throttle and analog pins was not as same as ADS pins, take solder and resolder analog pins to be same as ADS (A1 throttle, A2 brake, A3 clutch), plug in, start PedalFX calibrate and working like I expected (code attached ADS_PedalBox_1.4.1 and following files)

 

BUT!!!

 

Finally, I plugged pedals to my PC start game Asseto Corza Competizione and go to configure pedals in menu and when I try to bind pedals nothing. Start Project cars 2 binding pedals and game said that multiple inputs detected and I couldn't assign pedals. 

 

Back to start! 

Coding throttle as analog input, brake as digital and clutch as analog testing...both games assign pedals without any issue. I don't know about coding and assume that there is some catch in Pedal.h file to assign input signal for throttle int_channel=1 also for clutch channel 3 and for last couple of days I'm struggling to figure it out how to code this.



Regarding fact that I'm not familiar with coding maybe I'm on wrong path. Today just before I receive your mail I upload library from https://github.com/dmadison/Sim-Racing-Arduino and it is working but your is more refine and I would like to use your code.

 

I playing with this issue for few weeks now and I would really appreciate if you can help me, I think it is just the matter of coding.

 

Please be so kind and help if can and if you have time. I hope that you can help me to resolve this issue.

 

Thank you in advance.

 

Best regards!

 

Andrija
